  env: DEV
  tls:
    cert: cert.pem
    key: key.pem
  server:
    host: localhost
    port: 8081
  spotify:
    client_id: 
    client_secret: 
    redirect_uri: http://localhost:8080/callback/spotify
  auth:
    jwt_key: bXlzZWNyZXRrZXkK
